### ISSUE TITLE
Changing All Notes to Long Notes in osu!mania map

### ISSUE THREAD

**Issue by zombozo12** [smoogipoo/osu--BPM-Changer#2]
I'm so happy when I got this program because program from Hydria doesn't work on my laptop. So I tried this programs, it's still corrupted but it works when I play the beatmap. Then I see in Edit mode, all of the converted notes was changed to long note. I know I'm late 4 years, but it's a bug that developer should fix.

I hope you read my issue and fix it.
Best Regards,

Wiguna R

**Comment by Kontorted** [comment]
Im quite certain smoogipooo made it clear majority of his programs work only for osu!standard.

**Comment by smoogipooo** [comment]
@Kontorted This is correct. I haven't implemented functionality for non-osu!standard at all. I don't know when I'll have the time to fix/update all my apps but will look into the possibility of doing so within the next month.

**Comment by smoogipoo** [comment]
I don't have the time to work on this, sorry. Please consider using another tool like osu-trainer instead.
