### ISSUE TITLE
Couldn't create a SSL/TLS secure channel

### ISSUE THREAD

**Issue by KissMyUSSR** [smoogipoo/osu--BPM-Changer#7]
When I try to install osu!trainer an error System.Net.WebException pops off saying that it couldn't create an SSL/TLS secure channel.
I've set "check for updates" option to false, and now no errors appear, but the app doesn't work anyways.
Sorry for Russian language on the screenshots but it basically says what I've just said "couldn't create an SSL/TLS secure channel".
This issue is dedicated to FunOrange's osu!trainer, but after half an hour of trying to understand how to make an issue on it I've given up.
![image](https://user-images.githubusercontent.com/52123816/105470154-4367bd80-5caa-11eb-8439-2a5a34abcfcf.png)
![image](https://user-images.githubusercontent.com/52123816/105470184-4a8ecb80-5caa-11eb-8aa9-1abec3a2faf8.png)

**Comment by smoogipoo** [comment]
Please make an issue on funorange's fork instead: https://github.com/FunOrange/osu-trainer. It's almost completely disjoint from this project at this point.
