### ISSUE TITLE
osu!trainer not working

### ISSUE THREAD

**Issue by Avoreas** [smoogipoo/osu--BPM-Changer#9]
Hello, I ran into a problem when launching the app, the app does not open. The log file is attached
I apologize if there are errors in the text, I have very bad English and therefore use a translator.

![image](https://user-images.githubusercontent.com/77195232/112664201-c5bb5c00-8e6a-11eb-96af-1a7e34dfab4a.png)

**Comment by Avoreas** [comment]
![image](https://user-images.githubusercontent.com/77195232/112664303-dd92e000-8e6a-11eb-851e-0c4e790771de.png)

**Comment by smoogipoo** [comment]
osu-trainer is not made by me. https://github.com/FunOrange/osu-trainer
